global_frame: $(arg robot_namespace)odom
rolling_window: true
inflation:
    inflation_radius: 0.2

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}