# footprint: [[-0.23, -0.19], [-0.23, 0.19], [0.23, 0.19], [0.23, -0.19]]
# footprint_padding: 0.01
robot_radius: 0.23
robot_base_frame: $(arg robot_namespace)base_link
update_frequency: 5.0
publish_frequency: 0.5
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.0
raytrace_range: 2.5
track_unknown_space: true

#layer definitions
static:
    map_topic: /$(arg robot_namespace)map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

