controller_frequency: 2.5
controller_patience: 15.0
recovery_behaviour_enabled: true
# heading_scoring: true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 1 # A tolerance on the goal point for the planner.

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 3.0
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0
  max_rot_vel: 2.0
  min_rot_vel: 0

  max_vel_trans: 3.0
  min_vel_trans: 0.1
  max_vel_theta: 2.0
  min_vel_theta: -2.0

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.26
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: false

  # # Forward Simulation Parameters
  sim_time: 5.0
  # sim_granularity: 0.02
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20
  penalize_negative_x: true

  # # Trajectory scoring parameters
  path_distance_bias: 1.0 # The weighting for how much the controller should stay close to the path it was given
  goal_distance_bias: 0.2 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  occdist_scale: 0.01 # The weighting for how much the controller should attempt to avoid obstacles
  # forward_point_distance: 0.325 # The distance from the center point of the robot to place an additional scoring point, in meters
  # stop_time_buffer: 0.2  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  # scaling_speed: 0.25 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  # max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by

  # # Oscillation Prevention Parameters
  # oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)

TebLocalPlannerROS:

  # odom_topic: odom
  # map_frame: /odom
    
  # Trajectory
  global_plan_via_point_sep: 0.5
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 2.0
  feasibility_check_no_poses: 5

  # Robot
          
  max_vel_x: 3.5
  max_vel_x_backwards: 0.01
  max_vel_theta: 2.5
  acc_lim_x: 1.5
  acc_lim_theta: 2.0
  min_turning_radius: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "circular"
    radius: 0.22 # for type "circular"
    # line_start: [-0.3, 0.0] # for type "line"
    # line_end: [0.3, 0.0] # for type "line"
    # front_offset: 0.2 # for type "two_circles"
    # front_radius: 0.2 # for type "two_circles"
    # rear_offset: 0.2 # for type "two_circles"
    # rear_radius: 0.2 # for type "two_circles"
    # vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

  # GoalTolerance
    
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.2
  free_goal_vel: False
    
  # Obstacles
    
  min_obstacle_dist: 0.05
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 0.2
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  inflation_dist: 0.05
  # Optimization
    
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.01
  weight_max_vel_x: 1
  weight_max_vel_theta: 1
  weight_acc_lim_x: 0.5
  weight_acc_lim_theta: 0.5
  weight_kinematics_nh: 100
  weight_kinematics_forward_drive: 100
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 5
  weight_obstacle: 100
  weight_dynamic_obstacle: 10 # not in use yet
  weight_viapoint: 1
  alternative_time_cost: False # not in use yet

  # Homotopy Class Planner

  enable_homotopy_class_planning: False
  enable_multithreading: False
  simple_exploration: False
  max_number_classes: 3
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: True